apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: es-data-svc
  labels:
    component: elasticsearch
    name: es-data-svc
spec:
  ports:
    - port: 9300
      targetPort: 9300
      protocol: TCP
  selector:
    role: data
    component: elasticsearch
