cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}
  max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}

network.host: ${NETWORK_HOST}

path:
  data: /data/data
  logs: /data/log

bootstrap:
  memory_lock: true

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

cloud:
  kubernetes:
    service: ${DISCOVERY_SERVICE}
    namespace: ${NAMESPACE}
discovery:
  zen:
    hosts_provider: kubernetes
    minimum_master_nodes: ${NUMBER_OF_MASTERS}

plugin.mandatory: discovery-kubernetes
searchguard:
  ssl:
    transport:
      keystore_filepath: certs/node-keystore.jks
      keystore_password: changeit
      truststore_filepath: certs/truststore.jks
      truststore_password: changeit
      enforce_hostname_verification: false
    http:
      enabled: true
      keystore_filepath: certs/node-keystore.jks
      keystore_password: changeit
      truststore_filepath: certs/truststore.jks
      truststore_password: changeit
